version: "3"

services:
  db:
    restart: always
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sairi
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: sairi
    #ports:
    #  - 23306:3306
    volumes:
      - db-data:/var/lib/mysql
    user: mysql
  api:
    restart: always
    image: inoueke-n/sairi-backend:0.2.1
    environment:
      NODE_ENV: production
    ports:
      - 20080:80
    depends_on:
      - db

volumes:
  db-data:

